### ISSUE TITLE
Concider adding the categories.html to the website

### ISSUE THREAD

**Issue by SteveALee** [mulberrysymbols/mulberry-symbols#17]
Now we have merged #16 to generated the categories.pdf via an intermediate html file we can add the html to the website. Then visitors can view the categories without a download.

The only obvious downside is the file is 34MB, largely as SVGs are all inline.

**Comment by gavinhenderson** [comment]
I am happy to help with this. Have you got any specific idea where you want this page added. Would you like it to be in the downloads section? Or presented in another way? 

One way to solve the file size is obviously to split it into multiple HTML files per category but obviously that requires more work a d might not be worth it.

**Comment by SteveALee** [comment]
@gavinhenderson Thanks very much for the offer of help.

Lets add a new ```The Symbols``` section before the ```Downloads``` section.  That can include a little text plus a few sample symbols (also addresses #18) and most importantly the link to the categories.html.

Then the bullet to download load the PDF can be tweeked.

The release process in te readme will also need to be updated to add "copy the catagories.htm to docs".

**Comment by SteveALee** [comment]
PS no need to split the file - just warn it's a big file next to the link.

**Comment by gavinhenderson** [comment]
@SteveALee perfect, I'll submit a PR for this in the next few days

**Comment by gavinhenderson** [comment]
Hey @SteveALee just a quick question (hope you dont mind) before I start just so my understanding is clear:

Are you wanting 'build:html' script added to the package.json? I see that this wouldn't require any code to be added just need to split the code so it can be run without the pdf generation?

**Comment by gavinhenderson** [comment]
@SteveALee Sounds perfect, ill start working on the PR

**Comment by SteveALee** [comment]
Fixed by #20
