### ISSUE TITLE
General Site Improvements

### ISSUE THREAD

**Issue by gavinhenderson** [mulberrysymbols/mulberry-symbols#21]
There are a few minor issues with the site that need to be fix.

- [ ] There is no Gemfile in the docs folder. For local development it must be present (github uses the default if its not present)
- [ ] Jekyll generates a __site folder that it uses to serve the webpage. This should be in the gitignore.
- [ ] The webpage title is `Vision | ["Mulberry Symbols"]` rather than `Vision | Mulberry Symbols`

**Comment by SteveALee** [comment]
I've not tried local building & test of the site but it makes sense to remove any barriers.

**Comment by SteveALee** [comment]
Thanks
