### ISSUE TITLE
Adjust Catagories.html to better match site style

### ISSUE THREAD

**Issue by SteveALee** [mulberrysymbols/mulberry-symbols#22]
Possibly also add a back link (but that must not appear on the PDF)

Also see #19 as version could appear on both HTML and PDF

**Comment by gavinhenderson** [comment]
Im happy to work on this task? :)

**Comment by gavinhenderson** [comment]
@SteveALee PR #26 means this can be closed :+1:

**Comment by SteveALee** [comment]
Thanks, I forgot to update the PR title.
