### ISSUE TITLE
Add a contents page to PDF and HTML page

### ISSUE THREAD

**Issue by gavinhenderson** [mulberrysymbols/mulberry-symbols#25]
Add a linkable contents section to the PDF and HTML file that has all of the categories to ease navigation

**Comment by SteveALee** [comment]
Yes I do like the idea. Especially if a multi column layout can be used to reduce depth. Looking at the Categories names only 2 columns would probably work.

As an asside, I just realised the HTML layout ideally should be responsive. That's another job thoughand probably not worth it as is so massive in it's current form.

**Comment by gavinhenderson** [comment]
@SteveALee This can be closed :+1:

Next time ill make sure one of my commits closes the issue

**Comment by SteveALee** [comment]
Oops, I meant to alter the PR title.

**Comment by SteveALee** [comment]
Fixed by #39
