### ISSUE TITLE
Work with Shay to merge cboard changes

### ISSUE THREAD

**Issue by SteveALee** [mulberrysymbols/mulberry-symbols#3]
- [x] more symbols from mulberry in SVG format which weren’t converted from WMF
- [ ] renamed some symbols for better machine translation - mainly all lowercase + few reorder phrase
- [ ] also we translated mulberry into 32 languages
- [x] And i managed to compress the SVG (I think it saves around 10mb in total without losing quality)

https://github.com/cboard-org/cboard/tree/master/public/symbols/mulberry

@shayc

**Comment by SteveALee** [comment]
> which weren’t converted from WMF

Note the source format wit hthe adobe illustrator files but probably ALL got exported to WMF and not SVG. Wmf was such a bad format that most symbols needed manual editing of wmfs so don't know if this had been done or not for the extra symbols

**Comment by SteveALee** [comment]
@shayc Can you provide more info on the 1st 2 points above? Thanks

**Comment by shayc** [comment]
Made a PR (#13) that fixes missing symbols, these are the remaining symbols that I converted once from the WMF folder that was in the older project.

**Comment by SteveALee** [comment]
Extra symbols now in ZIP. have to add categories - have made an issue just for that

**Comment by SteveALee** [comment]
Going to leave renaming and translations for now - translations may be better looked after by Global Symbols project
