### ISSUE TITLE
Support customisation of symbols

### ISSUE THREAD

**Issue by SteveALee** [mulberrysymbols/mulberry-symbols#62]
## Requirements

For now just changing colours of elements. Stretch goal more substantial, including aggregation of parts to make new symbols.

## Options

- build - Templated and build - most flexible but complex workflow
- CSS stylesheet referenced from the SVG  - runtime, might need IDs to select all parts
- CSS classes in SVG styled  in using context - add classnames  to SVG - restricted classes available

**Comment by rusnewman** [comment]
I've prototyped an approach that allows dynamic colouring of elements in the SVGs. This uses the third option of writing classes directly into the SVG files and styling them with standard, flexible CSS techniques.

### Class Name Convention
The general structure of the class is `aac-[feature]-[target-attribute]`.

- Prefixed `aac-` to help avoid class clashes.
- `[feature]` is the object that can be adapted. This prototype allows `hair` and `skin`. Future versions could include `eyes`, etc.
- `[target-attribute]` is the attribute that should be changed for the adaptation. In most cases, this will be `fill`, but could also be `stroke` (to change the outline of an SVG element).

This basic sample shows the `aac-hair-fill` and `aac-skin-fill` classes assigned on two squares, which are grey by default.
```SVG
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="400" height="400" viewBox="0 0 400 400">
	<rect fill="gray" class="aac-hair-fill" x="60"  y="150" rx="0" ry="0" width="100" height="100"/>
	<rect fill="gray" class="aac-skin-fill" x="240" y="150" rx="0" ry="0" width="100" height="100"/>
</svg>
```

### Applying Adaptations
Colour adaptations can be applied in various ways that most web developers will be familiar with. Some examples:

- Adding a `<style>` tag to the SVG itself, targeting the classes.
- When the SVG is embedded in another document...
  - Through a `<style>` tag in the parent document.
  - Through a `<style>` tag and CSS variables in the parent document, which allows easy targeting of individual symbols in a large DOM.

### Review
We have to cover situations where adapted symbols are...
- Generated by a service and delivered as a static asset. 
- Embedded in a dynamic web app that allows the colours to be edited, generating adaptations on-the-fly.
- And situations in between these extremes.

Having tested other approaches, this one has exhibited the most flexibility for developers. I've successfully produced adapted symbols as static assets (for embedding in a PDF) and as dynamic assets (in a web app that allows live colour changes).

Graphic designers can apply the classes when creating symbols in design software, so they are included in exported SVGs.

Looking at the suggested alternatives...

- _Build - Templated and build_
  - Not quite sure what this approach is, but happy to comment if you can explain.
- _CSS stylesheet referenced from the SVG_
  - Is great for SVGs where the colours will not change.
  - Requires some complex operations to change colours in the SVG without re-loading the SVG or replacing the stylesheet URL.
  - Forces developers to use an external stylesheet, locking out many of the other ways CSS can be applied.
  - **Conclusion**: Not recommended. Using standard CSS technique (optionally with CSS variables) facilitates easier adaptations gracefully and with more flexibility for developers.

### Future Considerations and Expansion

- Where a symbol contains more than one person, it may be desirable to edit feature colours independently. Could be achieved by assigning additional classes. e.g. `aac-person-1`, `aac-person-2`, etc.
- Consider allowing arbitrary elements in the SVG to be tagged. e.g. `aac-drink-fill` for water, orangeade, cola, etc.
